/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedPlaylistsRouteImport } from './routes/_authenticated.playlists'
import { Route as AuthenticatedMembershipRouteImport } from './routes/_authenticated.membership'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated.favorites'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated.discover'
import { Route as AuthenticatedBecomeArtistRouteImport } from './routes/_authenticated.become-artist'
import { Route as AuthenticatedArtistsRouteImport } from './routes/_authenticated.artists'
import { Route as AuthenticatedArtistDashboardRouteImport } from './routes/_authenticated.artist-dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedMusicIdRouteImport } from './routes/_authenticated.music.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlaylistsRoute = AuthenticatedPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembershipRoute = AuthenticatedMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBecomeArtistRoute =
  AuthenticatedBecomeArtistRouteImport.update({
    id: '/become-artist',
    path: '/become-artist',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedArtistsRoute = AuthenticatedArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArtistDashboardRoute =
  AuthenticatedArtistDashboardRouteImport.update({
    id: '/artist-dashboard',
    path: '/artist-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMusicIdRoute = AuthenticatedMusicIdRouteImport.update({
  id: '/music/$id',
  path: '/music/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/artist-dashboard': typeof AuthenticatedArtistDashboardRoute
  '/artists': typeof AuthenticatedArtistsRoute
  '/become-artist': typeof AuthenticatedBecomeArtistRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/playlists': typeof AuthenticatedPlaylistsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/music/$id': typeof AuthenticatedMusicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/artist-dashboard': typeof AuthenticatedArtistDashboardRoute
  '/artists': typeof AuthenticatedArtistsRoute
  '/become-artist': typeof AuthenticatedBecomeArtistRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/playlists': typeof AuthenticatedPlaylistsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/music/$id': typeof AuthenticatedMusicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/artist-dashboard': typeof AuthenticatedArtistDashboardRoute
  '/_authenticated/artists': typeof AuthenticatedArtistsRoute
  '/_authenticated/become-artist': typeof AuthenticatedBecomeArtistRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/membership': typeof AuthenticatedMembershipRoute
  '/_authenticated/playlists': typeof AuthenticatedPlaylistsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/music/$id': typeof AuthenticatedMusicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/artist-dashboard'
    | '/artists'
    | '/become-artist'
    | '/discover'
    | '/favorites'
    | '/home'
    | '/membership'
    | '/playlists'
    | '/profile'
    | '/music/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/artist-dashboard'
    | '/artists'
    | '/become-artist'
    | '/discover'
    | '/favorites'
    | '/home'
    | '/membership'
    | '/playlists'
    | '/profile'
    | '/music/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/artist-dashboard'
    | '/_authenticated/artists'
    | '/_authenticated/become-artist'
    | '/_authenticated/discover'
    | '/_authenticated/favorites'
    | '/_authenticated/home'
    | '/_authenticated/membership'
    | '/_authenticated/playlists'
    | '/_authenticated/profile'
    | '/_authenticated/music/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/playlists': {
      id: '/_authenticated/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AuthenticatedPlaylistsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/membership': {
      id: '/_authenticated/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof AuthenticatedMembershipRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/become-artist': {
      id: '/_authenticated/become-artist'
      path: '/become-artist'
      fullPath: '/become-artist'
      preLoaderRoute: typeof AuthenticatedBecomeArtistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/artists': {
      id: '/_authenticated/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof AuthenticatedArtistsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/artist-dashboard': {
      id: '/_authenticated/artist-dashboard'
      path: '/artist-dashboard'
      fullPath: '/artist-dashboard'
      preLoaderRoute: typeof AuthenticatedArtistDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/music/$id': {
      id: '/_authenticated/music/$id'
      path: '/music/$id'
      fullPath: '/music/$id'
      preLoaderRoute: typeof AuthenticatedMusicIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedArtistDashboardRoute: typeof AuthenticatedArtistDashboardRoute
  AuthenticatedArtistsRoute: typeof AuthenticatedArtistsRoute
  AuthenticatedBecomeArtistRoute: typeof AuthenticatedBecomeArtistRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMembershipRoute: typeof AuthenticatedMembershipRoute
  AuthenticatedPlaylistsRoute: typeof AuthenticatedPlaylistsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedMusicIdRoute: typeof AuthenticatedMusicIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedArtistDashboardRoute: AuthenticatedArtistDashboardRoute,
  AuthenticatedArtistsRoute: AuthenticatedArtistsRoute,
  AuthenticatedBecomeArtistRoute: AuthenticatedBecomeArtistRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMembershipRoute: AuthenticatedMembershipRoute,
  AuthenticatedPlaylistsRoute: AuthenticatedPlaylistsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedMusicIdRoute: AuthenticatedMusicIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
