/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedPlaylistsRouteImport } from './routes/_authenticated.playlists'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated.favorites'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated.discover'
import { Route as AuthenticatedArtistsRouteImport } from './routes/_authenticated.artists'
import { Route as AuthenticatedMusicIdRouteImport } from './routes/_authenticated.music.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlaylistsRoute = AuthenticatedPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArtistsRoute = AuthenticatedArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMusicIdRoute = AuthenticatedMusicIdRouteImport.update({
  id: '/music/$id',
  path: '/music/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/artists': typeof AuthenticatedArtistsRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/playlists': typeof AuthenticatedPlaylistsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/music/$id': typeof AuthenticatedMusicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/artists': typeof AuthenticatedArtistsRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/playlists': typeof AuthenticatedPlaylistsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/music/$id': typeof AuthenticatedMusicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/artists': typeof AuthenticatedArtistsRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/playlists': typeof AuthenticatedPlaylistsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/music/$id': typeof AuthenticatedMusicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/artists'
    | '/discover'
    | '/favorites'
    | '/home'
    | '/playlists'
    | '/profile'
    | '/music/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/artists'
    | '/discover'
    | '/favorites'
    | '/home'
    | '/playlists'
    | '/profile'
    | '/music/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/privacy'
    | '/terms'
    | '/_authenticated/artists'
    | '/_authenticated/discover'
    | '/_authenticated/favorites'
    | '/_authenticated/home'
    | '/_authenticated/playlists'
    | '/_authenticated/profile'
    | '/_authenticated/music/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/playlists': {
      id: '/_authenticated/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof AuthenticatedPlaylistsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/artists': {
      id: '/_authenticated/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof AuthenticatedArtistsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/music/$id': {
      id: '/_authenticated/music/$id'
      path: '/music/$id'
      fullPath: '/music/$id'
      preLoaderRoute: typeof AuthenticatedMusicIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedArtistsRoute: typeof AuthenticatedArtistsRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPlaylistsRoute: typeof AuthenticatedPlaylistsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedMusicIdRoute: typeof AuthenticatedMusicIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArtistsRoute: AuthenticatedArtistsRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPlaylistsRoute: AuthenticatedPlaylistsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedMusicIdRoute: AuthenticatedMusicIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
