
REVOKE EXECUTE ON FUNCTION public.has_role(TEXT, public.app_role) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.increment_song_plays(UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(TEXT, public.app_role) TO service_role;
GRANT EXECUTE ON FUNCTION public.increment_song_plays(UUID) TO service_role;

-- Allow anon/authenticated to read cover + audio via signed URLs generated by server.
CREATE POLICY "Storage covers readable via signed url" ON storage.objects
  FOR SELECT TO anon, authenticated USING (bucket_id = 'covers');
CREATE POLICY "Storage songs readable via signed url" ON storage.objects
  FOR SELECT TO anon, authenticated USING (bucket_id = 'songs');
